FROM node:20-alpine

WORKDIR /app


# Copy package.json trước để cache layer cài dependencies
COPY package*.json ./
RUN npm install

# Copy source code sau để tránh rebuild khi không thay đổi code
COPY . .

#Expose Nextjs dev port
EXPOSE 3000

#Run in dev mode (Turbopack enabled (Nextjs))
CMD [ "npm", "run", "dev" ]

RUN chown -R node:node /app
USER node