FROM node:22.14.0-alpine

WORKDIR /app

COPY  package*.json ./
RUN npm install

COPY . . 

#Expose Express server port
EXPOSE 5000

#Use nodemon for live reload
CMD [ "npm", "run", "dev" ]

RUN chown -R node:node /app
USER node