FROM node:22.14.0-alpine

WORKDIR /app


# Copy package.json trước để cache layer cài dependencies
COPY package*.json ./
RUN npm install

# Copy source code sau để tránh rebuild khi không thay đổi code
COPY . .

#Expose Express server port
EXPOSE 5000

#Use nodemon for live reload
CMD [ "npm", "run", "dev" ]

RUN chown -R node:node /app
USER node